# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TZwlwScLSqVBIdZyySr15pt3uVRGZ5BR
"""

import streamlit as st
st.title("furusawa")